apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: debezium-connector
  labels:
    strimzi.io/cluster: debezium
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: "mysql.db.svc"
    database.port: "3306"
    database.user: "debezium"
    database.password: "dbz"
    database.server.id: "184054"
    database.server.name: "dbserver-mysql"
    database.whitelist: "inventory"
    database.history.kafka.bootstrap.servers: "broker-kafka-bootstrap.kafka.svc:9092"
    database.history.kafka.topic: "mysql.schema-changes.inventory"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    transforms: "extract"
    transforms.extract.type: "io.debezium.transforms.ExtractNewRecordState"
    transforms.extract.add.fields: "op,table"    