apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium
  namespace: debezium
  labels:
    app: debezium
  annotations:
    strimzi.io/use-connector-resources: 'true'    
spec:
  bootstrapServers: 'broker-kafka-bootstrap.kafka.svc:9092'
  config:
    config.storage.replication.factor: -1
    config.storage.topic: debezium-cluster-configs
    group.id: debezium-cluster
    offset.storage.replication.factor: -1
    offset.storage.topic: debezium-cluster-offsets
    status.storage.replication.factor: -1
    status.storage.topic: debezium-cluster-status
  image: 'quay.io/redhatintegration/rhi-cdc-connect:2021-Q1'
  replicas: 1
  version: 2.7.0