camel:
  springboot:
    # The Camel context name
    name: New API
  component:
    servlet:
      mapping:
        contextPath: /*

spring:
  datasource:
    url: jdbc:mysql://localhost/inventory
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.jdbc.Driver

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# logging:
#   level:
#     root: DEBUG