---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: "new-api"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "io.example"
    name: "new-api"
  spec:
    ports:
    - name: "http"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app: "new-api"
      provider: "fabric8"
      group: "io.example"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "new-api"
      provider: "fabric8"
      version: "1.0-SNAPSHOT"
      group: "io.example"
    name: "new-api"
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: "new-api"
        provider: "fabric8"
        group: "io.example"
    template:
      metadata:
        labels:
          rht.prod_ver: "7.8"
          rht.comp_ver: "1.0-SNAPSHOT"
          rht.prod_name: "Red_Hat_Integration"
          rht.comp: "new-api"
          com.company: "Red_Hat"
          app: "new-api"
          provider: "fabric8"
          version: "1.0-SNAPSHOT"
          group: "io.example"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "example/new-api:latest"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 180
            successThreshold: 1
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 9779
            name: "prometheus"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
